---
title: "Problem Set 1"
output: html_document
---

```{r ps1-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Welcome to Problem Set 1.
In this problem set, we're going to continue working with the tbl containing NBA shooting statistics that we saw in [Lecture 1](lecture1.html).



1. Before starting each problem set, we'd like you to take a few minutes to review the lecture notes from today's lecture. See if you can understand what the code in each code block is doing. In particular, working with someone from your group, try to explain what is happening within each code block from the lecture.

2. Close and re-open RStudio. Navigate to your working directory and load the tidyverse. 

3. Following along with the code from Lecture 1, read-in the dataset `nba_shooting_small` and add columns for field goal percentage (FGP), three point percentage (TPP), and free throw percentage (FTP).

4. One criticism of FGP is that it treats 2-point shots the same as 3-point shots.
As a result, the league leader in FGP is usually a center whose shots mostly come from near the rim.
[effective Field Goal Percentage](https://en.wikipedia.org/wiki/Effective_field_goal_percentage) is a statistic that adjusts FGP to account for the fact that a made 3-point shots is worth 50% more than a made 2-point shot. 
The formula for eFGP is
$$ \text{eFGP} = \frac{\text{FGM} + 0.5 \times \text{TPM}}{\text{FGA}}.$$
Add a new column to the tbl containing eFGP.

5. Add a new column to the tbl that records the number of points scored
$$
\text{PTS} = \text{FTM} + 2 \times \text{FGM} + \text{TPM}
$$
Remember, FGM records the number of 2-point shots made as well as the number of 3-point shots made.

6. Both field goal percentage and effective field goal percentage totally ignore free throws.
One metric that accounts for all field goals, three pointers, and free throws is [true shooting percentage](https://en.wikipedia.org/wiki/True_shooting_percentage), whose formula is given by
$$
\text{TSP} = \frac{\text{PTS}}{2\times(\text{FGA} + 0.44\times \text{FTA})}.
$$
Add another column to the tbl for TSP
7. Arrange your tbl so that the players are sorted in increasing order of true shooting percentage. Which player is the best?

